Add/leather thigh cuffs
Project-Pandora-Game/pandora-assets pull request #288
Opened 2024-09-24 10:04 UTC by SandrinePDR

## References

_None_

## About The Pull Request

Added a new asset "leather thigh cuffs"

## Changelog

Authored by: Claudia & Sandrine

```md
Assets:
- [Leather thigh cuffs] New asset
```

## Checklist

- [X] The change has been tested locally
- [X] Licensing information and credits were filled in/modified for added/modified assets
- [X] I understand this change is licensed based on [Pandora's Asset Licensing](https://github.com/Project-Pandora-Game/pandora-assets/blob/master/ASSET_LICENSING.md) information

2024-09-24 19:16 UTC, ClaudiaMia requested changes
In case you were looking for all instances of washed out weirdness I found more:

![image](https://github.com/user-attachments/assets/4d8d3ff7-4545-49da-b7c7-5f2fa873677a)

Also how the automatic sitting transformation looks is something that needs getting used to I guess~
![image](https://github.com/user-attachments/assets/b5f7ebd7-2920-4f6d-9ca7-3c8bfd955ad5)

From -5 to -2 the connected chain disappears when kneeling or sitting:
![image](https://github.com/user-attachments/assets/7cee7286-7f57-44d2-b7a3-cfd02fac188e)

When kneeling and sitting with 2/2 and some other values, the chain also disappears:
![image](https://github.com/user-attachments/assets/50cf5fb3-17d9-488b-97dd-c36e88007870)

2024-09-24 19:17 UTC, ClaudiaMia commented on src/assets/foot_restraints/leather_ankle_cuffs/graphics.json
> +									"operator": "<",
Note that the above comment is about the ankle cuffs not the thigh ones.

2024-09-26 19:34 UTC, Jomshir98 requested changes
Even if it made sense, we really don't want fully-rendered and composited images in this repo.
File in question: `src/assets/foot_restraints/leather_thigh_cuffs/leatherthighcuffs_chain_kneeling_short.png`

2024-09-26 19:37 UTC, SandrinePDR commented
You're correct. That was created by a misclick...

2024-09-29 14:46 UTC, ClaudiaMia commented
There are still some more visual artifacts with the rings. I will (hopefully) be able to address them through further changes to https://github.com/Project-Pandora-Game/pandora-assets/pull/291 .

So for now we will have to keep this one open until I could fix these.

2024-09-30 20:10 UTC, ClaudiaMia approved these changes
All fixed and working.

2024-09-30 20:27 UTC, Jomshir98 approved these changes

2024-09-30 20:31 UTC, merged