[ADD] Gloves
Project-Pandora-Game/pandora-assets pull request #309
Opened 2024-12-05 10:48 UTC by SandrinePDR

## References

_None_

## About The Pull Request

Added a new accessoire 'gloves' with different lengths and a first sample pattern.
Whoever likes to add transparency or shine for a latex effect, is welcome to do so.

## Changelog

Authored by: Taja & Sandrine

```md
Assets:
- [Glove] New asset
- [Body] Added missing poses for hands with spread fingers and backward rotation
```

## Checklist

- [X] The change has been tested locally
- [X] Licensing information and credits were filled in/modified for added/modified assets
- [X] I understand this change is licensed based on [Pandora's Asset Licensing](https://github.com/Project-Pandora-Game/pandora-assets/blob/master/ASSET_LICENSING.md) information

2024-12-05 13:53 UTC, Jomshir98 requested changes
Code and body changes look good!
Image-wise it stands out a bit weirdly to me, that some base images of the gloves are noticeably darker than others, which can look a bit weird when changing poses. Please let me know how you decide to go forward with this.
Also looking at them a bit closer, it is possible that just running the darker images through color normalization script might resolve this; if you would like my help on that feel feel to say so~

2024-12-05 13:55 UTC, Jomshir98 commented
Just found one more issue: The length of gloves can change between some poses. This is especially problematic in combination with "pattern", as then the pattern clips outside of the glove.
Example where this is visible quite a bit is "Regular gloves"+"Print" + fists + change hand rotation and watch right hand.

2024-12-05 13:56 UTC, Jomshir98 commented on src/assets/accessories/gloves/gloves.asset.ts
> +			'Accessory',
```suggestion
			'Gloves',
```

2024-12-05 14:20 UTC, SandrinePDR commented on src/assets/accessories/gloves/gloves.asset.ts
> +			'Accessory',
Changed...

2024-12-11 11:23 UTC, SandrinePDR commented
This asset is on hold, until #313 has been resolved

2025-01-25 17:17 UTC, ClaudiaMia approved these changes

2025-01-26 15:53 UTC, Jomshir98 approved these changes
I updated the preview image to match the changes done. With that out of the way, looks good to me!

2025-01-26 17:20 UTC, merged